### ISSUE TITLE
problems with brandi Onepage HTML5 Business Template

### ISSUE THREAD

**Issue by domenicant** [themefisher/themefisher.github.io#1]
Hi,
I found the following problems with brandi html5 template:

- I'm not able to change the header color.
When you scroll the page down the header is turquoise. I would like red. I checked in stylesheet but I can't find the code line that corresponds to the setting of color.

- In the mobile version I want to zoom out the slideshow image. Now it's too big. What should I change?

Thanks for your help.

Domenica

**Comment by themefisher** [comment]
Hello Domenica,
Thanks for contacting with me.All of my templates are totally free . But if you need any customization then you have to buy $10 service pace. For more help contact with me through themefisher@gmail.com
Thanks
